### ISSUE TITLE
AUR package?

### ISSUE THREAD

**Issue by Vresod** [MatthiasCoppens/pulseaudio-virtualmic#1]

**Comment by MatthiasCoppens** [comment]
I'm looking into creating one, I only haven't got a running Arch system laying around at the moment

**Comment by Vresod** [comment]
i do :)

**Comment by MatthiasCoppens** [comment]
Feel free :), my [GURU ebuild](https://gitweb.gentoo.org/repo/proj/guru.git/tree/media-sound/pulseaudio-virtualmic/pulseaudio-virtualmic-0.1.ebuild) places it in /usr/bin.
